name: Azure Function CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Archive function app
        run: |
          zip -r functionapp.zip .

      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: <YOUR_FUNCTION_APP_NAME>
          package: functionapp.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
